name: deploy-marketing

on:
  push:
    branches:
      - master
    paths:
      - "marketing/**"

defaults:
  run:
    working-directory: marketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Replace with your desired Node.js version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1 # Change this to your desired AWS region
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Install Dependencies in Marketing
        run: npm install # Install dependencies in the container directory

      - name: Build
        run: npm run build # Use 'npm run build' if you're using npm
        # env:
        # PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Deploy to AWS S3
        uses: shinyinc/action-aws-cli@v1.2
        with:
          args: s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Debug AWS CLI Command
        run: |
          echo "AWS CLI Command: aws s3 sync dist s3://microfrontenddemo/marketing/latest"
          aws s3 sync dist s3://microfrontenddemo/marketing/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1" # Change to your region

      - name: Cache Invalidation debug
        run: |
          echo "Cache Invalidate aws cloudfront create-invalidation"
          aws cloudfront create-invalidation --distribution-id "E16490P5VBD107" --paths "/marketing/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
